#!/usr/bin/env bash
set -Eeuo pipefail

# wrapper for kustomize build to be used with xargs in vlux script

file="$1"
shift 1

kustomize build \
          --load-restrictor=LoadRestrictionsNone \
          --reorder=legacy \
          "$file" \
  | "$@"
