#!/usr/bin/env bash
set -Eeu # no -o pipefail on purpose to allow commands to succeed when no yaml files are present

dir="$1"

echo "Running yamllint ..."
YAMLLINT_CONFIG_FILE=/usr/local/share/yamllint/config.yaml \
  yamllint "$dir"

echo "Running kubeval on input files ..."
ag --vimgrep -lg '\.yaml$' "$dir" \
  | xargs -r kubeval --strict \
                     --schema-location="https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master" \
                     --additional-schema-locations="file:///usr/local/share/schemas" \
                     --ignore-missing-schemas

echo "Running kubeval on built kustomizations ..."  
ag --vimgrep -lg 'kustomization\.yaml' "$dir" \
  | sed -e 's|/kustomization.yaml$||g' \
  | xargs -r -n1 -I{} kustomization {} \
                      kubeval - \
                              --strict \
                              --schema-location="https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master" \
                              --additional-schema-locations="file:///usr/local/share/schemas" \
                              --ignore-missing-schemas \
                              --filename {}
