name: Pull Request

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Hadolint
        run: docker compose run --rm hadolint Dockerfile
      - name: Shellcheck
        run: docker compose run --rm shellcheck tools/*

  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Build
        uses: docker/build-push-action@v3.1.1
      - name: Build Test
        uses: docker/build-push-action@v3.1.1
        with:
          target: test
      - name: Test
        run: DOCKER_BUILDKIT=1 docker compose run --rm bats test
