name: Push to main

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.3
      - name: Hadolint
        run: docker compose run --rm hadolint Dockerfile
      - name: Shellcheck
        run: docker compose run --rm shellcheck tools/*

  build-test-push:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.3
      - name: Login to Docker
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v5.3.0
      - name: Build Test
        uses: docker/build-push-action@v5.3.0
        with:
          target: test
      - name: Test
        run: DOCKER_BUILDKIT=1 docker compose run --rm bats test
      - name: Push
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          tags: technowledgy/vlux:latest

  dockerhub:
    needs: build-test-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.3
      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}